### ISSUE TITLE
Expression Mapper Implementation

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo-lib#126]
Ability to use functions and expressions within mapping logic. for example, concat(), etc

**Comment by mellistibco** [comment]
At the moment, there is no function contribution model for mappings. The only supported functions should be implemented within the expression mapper

**Comment by vijaynalawade** [comment]
@lixingwang : Lets start on porting mapper capabilities.

**Comment by lixingwang** [comment]
Fixed at https://github.com/TIBCOSoftware/flogo-lib/pull/127
