### ISSUE TITLE
exists function in mapper 

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo-lib#150]
Add an `exists` function to the mapper to support a scenario where a flow developer wants to check if a property is not nil/exists. For example on a branch:

exists($activity[rest_2].result.photoUrls) == true

**Comment by mellistibco** [comment]
It seems we have a isDefined for the linker, we should add this as a general mapper function...

**Comment by lixingwang** [comment]
for undefine or empty field we can use `$activity[rest_2].result.photoUrls == nil` to check.
