### ISSUE TITLE
Consistent naming for environment variables

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo-lib#156]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] enhancement request
[ ] feature request
[ ] support request
[ ] general question
```

**Current behavior (how does the issue manifest):**
Env var name STOP_ENGINE_ON_ERROR is not consistent with other vars e.g. FLOGO_LOG_LEVEL
**Expected behavior:**
Name should be FLOGO_ENGINE_STOP_ON_ERROR
**Minimal steps to reproduce the problem (not required if feature enhancement):**
NA
**What is the motivation / use case for changing the behavior?**
Consistency 
**Please tell us about your environment (Operating system, docker version, browser & verison if webui, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
0.5.2
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vijaynalawade** [comment]
In this particular case, I feel backward compatibility is not needed. @mellistibco ??

**Comment by mellistibco** [comment]
I agree with @vijaynalawade. probably don't need it for this one
