### ISSUE TITLE
Incorrect evaluation of expression with mixed int and float values

### ISSUE THREAD

**Issue by balamg** [TIBCOSoftware/flogo-lib#245]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] enhancement request
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
The expression
`expression.ParseExpression("1 == 1.23")`evaluates to true which is incorrect. However, `expression.ParseExpression("1.23 == 1")` evaluates to false, which is expected

**Expected behavior:**
expression.ParseExpression("1 == 1.23") should evaluate to false

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Run these tests
```
func Test_Eval (t *testing.T) {
	expr, _ := expression.ParseExpression("1 == 1.23")
	i, err := expr.Eval()
	if err != nil {
		t.Fatalf("error %s\n", err)
	}
	res := i.(bool)
	if res {
		t.Errorf("Expected false, got : %t\n ", res)
	}
}

func Test_Eval2 (t *testing.T) {
	expr, _ := expression.ParseExpression("1 < 1.23")
	i, err := expr.Eval()
	if err != nil {
		t.Fatalf("error %s\n", err)
	}
	res := i.(bool)
	if !res {
		t.Errorf("Expected true, got : %t\n ", res)
	}
}

func Test_Eval3 (t *testing.T) {
	expr, _ := expression.ParseExpression("1.23 == 1")
	i, err := expr.Eval()
	if err != nil {
		t.Fatalf("error %s\n", err)
	}
	res := i.(bool)
	if res {
		t.Errorf("Expected false, got : %t\n ", res)
	}
}

func Test_Eval4 (t *testing.T) {
	expr, _ := expression.ParseExpression("1.23 > 1")
	i, err := expr.Eval()
	if err != nil {
		t.Fatalf("error %s\n", err)
	}
	res := i.(bool)
	if !res {
		t.Errorf("Expected true, got : %t\n ", res)
	}
}
```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & verison if webui, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by lixingwang** [comment]
Thanks @balamg, I will take a look.
