### ISSUE TITLE
Ability to get output complex_object attributes metadata from activity/trigger code

### ISSUE THREAD

**Issue by lixingwang** [TIBCOSoftware/flogo-lib#45]
There is no way to get metadata field from output complex_object attribute inside activity/trigger code,  we might need the schemas in activity/trigger code to do validation or show the structure of the fields.

Take example: I define a activity.trigger with complex_object output attribute call “response”.  Today, no way to get this field from activity/trigger code.

**Comment by fm-tibco** [comment]
For an activity output that is a complex_object, if its metadata is set at runtime, that metadata should be configured via an activity input.

**Comment by vijaynalawade** [comment]
Based on recent discussions, reopening this issue.
