### ISSUE TITLE
Ability to set customized log format

### ISSUE THREAD

**Issue by lixingwang** [TIBCOSoftware/flogo-lib#51]
Ability to set customized log format or change log format to fit TCI format.

**%H:%M:%S.000 logLevel messages**

Sample:
21:10:01.920 INFO  [mockAppThread:215] app.js - API Mock App Server started successfully on 0.0.0.0 with port 7002.

**Comment by vijaynalawade** [comment]
Date/Time format can be controlled through LOG_DATETIME_FORMAT environment variable.
In  TCI, set LOG_DATETIME_FORMAT="15:04:05.000"
