### ISSUE TITLE
Support for activity configuration/settings

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo-lib#53]
Like triggers, activities should be allowed to set static configuration in settings.

e.g. 
{
	"name": "tibco-wi-sendmail",
	"version": "1.0.0",
	"title": "Send Mail",
	"description": "Simple Send Mail Activity",
	"category": "Mail",
	"settings": [
		{
			"name": "server",
			"type": "string",
			"required": true,
			"value": "mail.example.com"
		},
		{
			"name": "port",
			"type": "string",
			"required": true,
			"value": "25"
		},
		{
			"name": "username",
			"type": "string",
			"value": ""
		},
		{
			"name": "password",
			"type": "string",
			"value": ""
		}
	],
	"inputs": [
		{
			"name": "sender",
			"type": "string",
			"required": true,
			"value": "sender@example.net"
		},
		{
			"name": "recipients",
			"type": "string",
			"required": true,
			"value": "recipient1@example.net,recipient2@example.net"
		},
		{
			"name": "subject",
			"type": "string",
			"value": ""
		},
		{
			"name": "message",
			"type": "string",
			"value": ""
		}
	]
}

**Comment by vijaynalawade** [comment]
Based on discussion, activity developer should tag/label input field to place it either as  settings or as inputs.

**Comment by fm-tibco** [comment]
If a category for an activity input is required like "setting", a tag can be added to the input that can be used to identify this.

example:

`{
"name": "port",
"type": "string",
"required": true,
"tags": ["setting"]
}
`
