### ISSUE TITLE
Error handling for link expr

### ISSUE THREAD

**Issue by flogo-oss** [TIBCOSoftware/flogo-lib#83]
From an end user, they need error handler while executing branching linker. 

Any error happening inside link should trigger error handler(Erro flow).

Add error return for EvalLinkExpr and make sure the error handled by engine

```
type LinkExprManager interface {

	// EvalLinkExpr evaluate the link expression
	EvalLinkExpr(link *Link, scope data.Scope) bool
}

```

**Comment by lixingwang** [comment]
The issue open by @lixingwang
