### ISSUE TITLE
Concatenation in inputMappings

### ISSUE THREAD

**Issue by jvanderl** [TIBCOSoftware/flogo-lib#9]
I would like to be able to concatenate multiple elements as input for a mapping.

From what I can see (judging from mapping.go), this should probably have to be a type:3 (MtExpression) mapping and then following a certain syntax in the value element, which seems to be not yet implemented. Would this be the way forward, or is there another way to achieve this (without writing a specific activity for this)?

Thanks,

Jan.

**Comment by mellistibco** [comment]
Added in #137 and will be included in the 0.5.2 release
